name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-with-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Save jar as artifact
        uses: actions/upload-artifact@v2
        with:
          name: PlayerEventsDiscord.jar
          path: build/libs/PlayerEventsDiscord*.jar